[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirect API requests to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle React/Vite routes for success and cancel pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
